name: Deploy Fabric Benchmarking Workspace

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run provisioning script
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CAPACITY_ID: ${{ secrets.CAPACITY_ID }}
          ADMIN_OBJECT_ID: ${{ secrets.ADMIN_OBJECT_ID }}
        run: |
          python scripts/provision_workspace.py
