name: Provision Fabric Benchmarking Workspace

on:
  workflow_dispatch:

jobs:
  provision-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run provisioning script
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CAPACITY_ID: ${{ secrets.CAPACITY_ID }}
          ADMIN_OBJECT_ID: ${{ secrets.ADMIN_OBJECT_ID }}
        run: |
          python scripts/provision_workspace.py

      - name: Upload workspace ID artifact
        uses: actions/upload-artifact@v4
        with:
          name: workspace-id
          path: .state/workspace_id.txt
